/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f9f9ff",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-high": "#e1e8fd",
        "secondary-fixed-dim": "#b7c8e1",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f3ff",
        "tertiary-fixed-dim": "#4edea3",
        "outline": "#777587",
        "surface": "#f9f9ff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#3323cc",
        "background": "#f9f9ff",
        "on-tertiary-fixed": "#002113",
        "tertiary": "#005338",
        "primary": "#3525cd",
        "on-primary-container": "#dad7ff",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-surface": "#141b2b",
        "surface-container": "#e9edff",
        "secondary-container": "#d0e1fb",
        "on-background": "#141b2b",
        "surface-dim": "#d3daef",
        "inverse-primary": "#c3c0ff",
        "on-primary": "#ffffff",
        "outline-variant": "#c7c4d8",
        "on-secondary-fixed-variant": "#38485d",
        "on-primary-fixed": "#0f0069",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#c3c0ff",
        "on-surface-variant": "#464555",
        "on-secondary-fixed": "#0b1c30",
        "on-tertiary-fixed-variant": "#005236",
        "primary-fixed": "#e2dfff",
        "inverse-surface": "#293040",
        "primary-container": "#4f46e5",
        "secondary": "#505f76",
        "tertiary-container": "#006e4b",
        "surface-tint": "#4d44e3",
        "on-secondary-container": "#54647a",
        "on-tertiary-container": "#67f4b7",
        "surface-container-highest": "#dce2f7",
        "error": "#ba1a1a",
        "inverse-on-surface": "#edf0ff",
        "on-error-container": "#93000a",
        "secondary-fixed": "#d3e4fe",
        "surface-variant": "#dce2f7"
      },
      spacing: {
        "base": "8px",
        "gutter": "24px",
        "sm": "8px",
        "lg": "24px",
        "container-max": "1280px",
        "xxl": "48px",
        "xl": "32px",
        "xs": "4px",
        "md": "16px"
      },
      fontFamily: {
        "label-md": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
        "headline-sm": ["Inter"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "label-lg": ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"]
      },
      fontSize: {
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["11px", { "lineHeight": "16px", "fontWeight": "500" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
};
